# Generated by Django 5.2.9 on 2026-01-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
