FROM node:20

# Install Apache
RUN apt-get update && apt-get install -y apache2 apache2-utils \
    && rm -rf /var/lib/apt/lists/*

# Enable Apache modules
RUN a2enmod proxy \
    && a2enmod proxy_http \
    && a2enmod headers

# Working directory
WORKDIR /var/www/html/smart_inventory_fe

# Copy code (optional, volume will override)
COPY . /var/www/html/smart_inventory_fe

# Expose ports
EXPOSE 80
EXPOSE 3000

# Start Apache only
CMD ["apache2ctl", "-D", "FOREGROUND"]
