# Generated by Django 5.2.9 on 2026-01-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_product_customerorderitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
